### ISSUE TITLE
Error at start, connection failed : connection refused

### ISSUE THREAD

**Issue by Luis-omega** [whonore/Coqtail#154] opened 2020-11-07 22:56 UTC
Hi.

I just installed Coqtail in neovim (NVIM v0.5.0-801-ga061d53e1) using vimplug and every time I do a `<leader>cc` it says : 

```
Se ha detectado un error al procesar function coqtail#start[6]..coqtail#init[19]..<SNR>59_open:
línea    2
connection failed: connection refused
```

The file I'm using is 

```
Inductive day : Type :=
| monday
| tuesday
| wednesday
| thursday
| friday
| saturday
| sunday.
```

I'm using Python 3.8.6

I follow the error to this call

```
    call b:coqtail_chan.open('localhost:' . s:port)
```

an echom of the port shows that 

```
    let s:port = coqtail#compat#pyeval(printf(
      \ 'CoqtailServer.start_server(bool(%d))', !g:coqtail#compat#has_channel))
```

returns a port, but a call to nmap 

```
nmap localhost -p port
```

show port as closed. 

I think it could be a couple of things 

- CoqtailSever is configured but never runs, I haven't work with `six.py` before, so I'm not sure how it works.

- CoqtailSever starts, but crashes.

As I said, I'm not familiar with `six.py`, so I don't even know how to start to debug this, so, please, help.

**Comment by whonore** [comment] 2020-11-08 22:53
Thanks for the detailed report. I doubt the problem is related to `six.py` since that's just for compatability between Python 2 and 3. Since you say `CoqtailServer.start_server` returns a port then, assuming it's not returning -1, it seems like your second guess might be right and the server is crashing/closing right after starting.

I'm not able to reproduce this issue with NeoVim v0.4.4 so I wonder if that's related. I haven't had any luck yet getting v0.5 to work for me yet so I can't confirm. I'll keep trying, but in the meantime if it's not too hard for you to get a working v0.4.4 it would be very helpful if you could check if you encounter the same issue there. Or with regular Vim.

**Comment by Luis-omega** [comment] 2020-11-09 11:32
Hi.
Thanks for the fast reply.

Yes, the port isn't `-1`, is a random positive number.

I have a laptop with almost the same configurations that my main pc, Coqtail works on nvim 0.5 in that laptop.

I updated neovim to last branch (since laptop was a commit over pc) and nothing changes.

Open a file with vim returns :

```
Failed to launch Coq.
```

So I follow the script and since it is in this point, coqtail was able to found my coqtop.opt binary and check version.

I added echoms to the last call and tried on vim

```vim
    " Launch Coqtop
    let [l:ok, l:msg] = s:call('start', 'sync', 0, {
      \ 'version': b:coqtail_version,
      \ 'coq_path': expand(coqtail#util#getvar([b:, g:], 'coqtail_coq_path', '')),
      \ 'coq_prog': coqtail#util#getvar([b:, g:], 'coqtail_coq_prog', ''),
      \ 'args': map(copy(l:proj_args + a:000), 'expand(v:val)')})
    echom "version: " . b:coqtail_version
    echom "coq_path"
    echom expand(coqtail#util#getvar([b:, g:], 'coqtail_coq_path', ''))
    echom "coq_prog" 
    echom  coqtail#util#getvar([b:, g:], 'coqtail_coq_prog', '')
    echom "args"
    echom  map(copy(l:proj_args + a:000), 'expand(v:val)')
    if !l:ok || l:msg != v:null
      let l:msg = l:ok && l:msg != v:null ? l:msg : 'Failed to launch Coq.'
      call coqtail#util#err(l:msg)
      call coqtail#stop()
      return 0
    endif
```

and this is the message:

``` 
version: 8.12.0
coq_path
coq_prog
args
[]
Failed to launch Coq.
```

If I set `let g:coqtail_coq_path = '/bin'` then the output is 

```
version: 8.12.0
coq_path
/bin/
coq_prog
args
[]
Failed to launch Coq.
```

out put of `vim --version`
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Parches incluidos: 1-1704
Compilado por Arch Linux
```

Since Coqtail can get the version of my coqtop it probably isn't a permission issue for the server.

Just in case, coqide works.

**Comment by whonore** [comment] 2020-11-09 20:54
Since `msg` is `-1` I'm guessing `s:call` is failing because `s:running()` is returning false. You could try adding `echom v:errmsg` in the `catch` branch to see if that tells you anything useful. The code for `CoqtailServer` is in python/coqtail.py. If you are in the Coqtail directory you can run `PYTHONPATH=python python -i -c 'from coqtail import CoqtailServer; print(CoqtailServer.start_server(False))'` to start the server manually and then use `nmap` to check if it closes when started that way.

**Comment by Luis-omega** [comment] 2020-11-10 13:17
I tried the `echom` you proposed but nothing was printed. I read the "how to debug vim" and got a log of 5k lines, if you ran 

`:g/^line \|^Searching\|^chdir\|^fchdir\|^finished sourcing/d`

you get a 1k file (and if you delete empty lines is a 500 lines file), I upload both of them (I ran a  `:%s:/home/username/:$HOME/:g` on the file) to 

https://gist.github.com/Luis-omega/fc207cde6373baaee32f3528f69bf983

and I did a 

```
python -i -c 'from coqtail import CoqtailServer'
>>> print(CoqtailServer.start_server(False))
58561
```

```
nmap localhost -p 58561
Starting Nmap 7.80 ( https://nmap.org ) at 2020-11-10 07:15 CST
Nmap scan report for localhost (192.168.100.2)
Host is up (0.00018s latency).
Other addresses for localhost (not scanned): ::1

PORT      STATE  SERVICE
58561/tcp closed unknown

Nmap done: 1 IP address (1 host up) scanned in 0.10 seconds
```

**Comment by whonore** [comment] 2020-11-10 14:39
I see some lines that suggest the Netrw plugin is running ([like this](https://gist.github.com/Luis-omega/fc207cde6373baaee32f3528f69bf983#file-after-removing-all-sourcing-L105)). Is the file you're editing on a different machine than where Vim is running? But I guess that still wouldn't explain why starting the server manually doesn't work either. Maybe a firewall is closing certain ranges of ports?

**Comment by Luis-omega** [comment] 2020-11-10 21:32
No, in that attempt i just `vim some.v` with a local empty file. 

I don't have a firewall... 

It must be the lsp plugin since the full output has 

```
Searching for "$HOME/.vim-plugins/LanguageClient-neovim/scripts.vim"
Executing:  endif
Executing BufNewFile Autocommands for "*"
autocommand if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf FALLBACK conf | endif

Executing: if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf FALLBACK conf | endif
Executing:    setf FALLBACK conf | endif
Executing:  endif
Executing BufEnter Autocommands for "*"
autocommand sil call s:LocalBrowse(expand("<amatch>"))
```

**Comment by whonore** [comment] 2020-11-12 14:34
Hm, I'm running out of ideas, but it's looking to me like it isn't directly related to Vim or Coqtail, but rather something to do with sockets being closed. Just to check, could you try running `python -c 'from socketserver import *; s = ThreadingTCPServer(("localhost", 0), StreamRequestHandler); print(s.server_address); s.serve_forever()'` and then, with the python window still open, check the port in another window? It should do basically the same thing as the last python command I gave you, but this time without any dependency on Coqtail at all.

**Comment by Luis-omega** [comment] 2020-11-13 01:42
I'm sorry, you are right! 

I'm on  a fresh install of archlinux and it seems the configuration in /etc/hosts was wrong.

The weir thing is that ssh was working right so I never suspect on that! 

I'm sorry for all the time you spend on this and thanks.

**Comment by whonore** [comment] 2020-11-13 15:35
It's no problem, I'm glad we figured it out. Thanks for your help tracking down the problem.

**Closed by whonore** 2020-11-13 15:35 UTC
Labels: bug
