### ISSUE TITLE
Buffer is not modifiable after user interrupt

### ISSUE THREAD

**Issue by j-hui** [whonore/Coqtail#121] opened 2020-07-20 16:07 UTC
After hitting `<C-c>` to stop a buffer, I'm unable to modify the buffer:

```
E21: Cannot make changes, `modifiable` is off
```

Furthermore, when I manually override that with `:set modifiable`, as soon as I
invoke another Coqtail command, the buffer is left in the `nomodifiable` state
once again, even if I didn't interrupt it the second time.

**Comment by whonore** [comment] 2020-07-20 16:29
What version of Vim/NeoVim are you using? And does this happen every time you interrupt or inconsistently?

**Comment by j-hui** [comment] 2020-07-21 19:25
My vim version:

```:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       -python            +tag_binary        +vertsplit         -xpm
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3           +tag_old_static    +virtualedit       -xsmp
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +visual            -xterm_clipboard
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visualextra       -xterm_save
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +viminfo
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             -ruby              +terminal          +vreplace
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +wildignore
++builtin_terms    +cursorbind        +find_in_path      +langmap           +mouse_gpm         +path_extra        +signs             +termresponse      +wildmenu
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     -perl              +smartindent       +textobjects       +windows
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +writebackup
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             -X11
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -xfontset
-clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xim```

**Comment by j-hui** [comment] 2020-07-21 19:27
My impression had been that this happens consistently when I interrupt an
especially heavy tactic, but I have since encountered a few times when this
didn't occur (i.e. `modifiable` was successfully reset after I issued the user
interrupt).

**Comment by whonore** [comment] 2020-07-21 20:03
The reason `'modifiable'` isn't getting reset is probably because `coqtail#defaultCB` isn't getting called or it's being interrupted early. I think what's happening is `CTRL-C` is normally mapped to `CoqInterrupt`, but while Vim is executing a function it still treats it as an interrupt and stops what it's doing. I tried to account for this in a couple places with a try-catch, but apparently it's not enough. What I really need is a way to tell Vim to temporarily ignore interrupts, but I'm not sure that's possible.

**Comment by j-hui** [comment] 2020-07-21 23:12
Yeah, that seems to be it.

`:let b:cmds_pending` shows me that it still thinks that it still thinks there's a pending command, and manually setting it to zero (i.e. `:let b:cmds_pending = 0`) and rerunning a Coqtail command fixes the issue. Not sure that's the cleanest fix, but doing that resolves the issue for me.

**Comment by j-hui** [comment] 2020-07-21 23:13
It might be worth mentioning that I have `<C-c>` mapped as a prefix to my Coqtail commands (like Proof General). I'm not sure if that somehow changes how it's understood by Vim.

Also, this issue doesn't appear when I just run `:CoqInterrupt`. An alternative workaround might be to define and learn another binding for interrupting `coqtop`.

**Comment by whonore** [comment] 2020-07-22 00:09
Just using `:CoqInterrupt` or binding a different mapping to it shouldn’t have this problem. The issue is just that CTRL-C is used both for the coqtail mapping and to interrupt Vim. I’d like to keep using CTRL-C as the default since it’s probably what most people expect but if I can’t find a good fix for this I may need to change it.

**Comment by whonore** [comment] 2020-07-22 21:19
I'll keep this open because even if we can't completely resolve the Vim interrupt problem we could do more to work around it/make it clearer how a user can fix it if they run into the `nomodifiable` issue.

**Comment by j-hui** [comment] 2020-07-24 04:02
So, I've just been manually running `:let b:cmds_pending = 0` whenever that happens, and remembering to use `:CoqInterrupt` for long-running tactics.

I'm planning on just adding my own bindings to make those a little faster (and maybe make the `:let` invocation a little smarter to handle multiple commands in flight, thought that doesn't happen very often if at all). Not sure if either of those are viable workarounds?

**Comment by whonore** [comment] 2020-07-24 11:50
Mapping something other than CTRL-C to `:CoqInterrupt` is definitely a viable workaround. `b:pending_cmds` is an implementation detail that you shouldn’t have to mess with manually but I have some ideas for handling that better.

When you encounter this problem is it after you press CTRL-C once or do you spam it a couple times?

**Comment by j-hui** [comment] 2020-07-26 21:45
I tend to spam it a couple of times. I have `<C-c>` set as a mapping prefix to other Coqtail commands (to preserve the `<C-c><enter>` shortcut from Proof General), so it's sort of a habit..

**Comment by whonore** [comment] 2020-08-07 18:33
@j-hui If you get a chance could you try out [this branch](https://github.com/whonore/Coqtail/tree/catch-interrupt) and see if that helps at all? I stopped seeing the `nomodifiable` not getting reset problem, but I was only able to reproduce it pretty rarely to begin with.

**Comment by j-hui** [comment] 2020-08-08 19:39
I'll keep an eye out for this.

**Comment by whonore** [comment] 2020-09-05 20:46
I've been using #130 for a while now without running into this problem so I'm tentatively closing this issue. Feel free to reopen or open a new one if it comes up again.

**Closed** 2020-09-05 20:45 UTC
Labels: bug
